plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.mlkittextrecognition'
version = '0.1.0'

android {
  namespace "expo.modules.mlkittextrecognition"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // Variante bundled: modelo dentro do APK — OCR 100% offline, sem Play Services.
  implementation("com.google.mlkit:text-recognition:16.0.1")
}
